
INSERT INTO	`user` (account, password, status, email, phone_number, registered_at, created_at, created_by) VALUES ('Test01', 'Test01', 'REGISTERED', 'Test01@test.com', '010-0000-0001', NOW(), NOW(), 'ADMIN');
INSERT INTO	`user` (account, password, status, email, phone_number, registered_at, created_at, created_by) VALUES ('Test02', 'Test02', 'REGISTERED', 'Test02@test.com', '010-0000-0002', NOW(), NOW(), 'ADMIN');
INSERT INTO	`user` (account, password, status, email, phone_number, registered_at, created_at, created_by) VALUES ('Test03', 'Test03', 'REGISTERED', 'Test03@test.com', '010-0000-0003', NOW(), NOW(), 'ADMIN');
INSERT INTO	`user` (account, password, status, email, phone_number, registered_at, created_at, created_by) VALUES ('Test04', 'Test04', 'REGISTERED', 'Test04@test.com', '010-0000-0004', NOW(), NOW(), 'ADMIN');
INSERT INTO	`user` (account, password, status, email, phone_number, registered_at, created_at, created_by) VALUES ('Test05', 'Test05', 'REGISTERED', 'Test05@test.com', '010-0000-0005', NOW(), NOW(), 'ADMIN');
INSERT INTO	`user` (account, password, status, email, phone_number, registered_at, created_at, created_by) VALUES ('Test06', 'Test06', 'REGISTERED', 'Test06@test.com', '010-0000-0006', NOW(), NOW(), 'ADMIN');
INSERT INTO	`user` (account, password, status, email, phone_number, registered_at, created_at, created_by) VALUES ('Test07', 'Test07', 'REGISTERED', 'Test07@test.com', '010-0000-0007', NOW(), NOW(), 'ADMIN');
INSERT INTO	`user` (account, password, status, email, phone_number, registered_at, created_at, created_by) VALUES ('Test08', 'Test08', 'REGISTERED', 'Test08@test.com', '010-0000-0008', NOW(), NOW(), 'ADMIN');
INSERT INTO	`user` (account, password, status, email, phone_number, registered_at, created_at, created_by) VALUES ('Test09', 'Test09', 'REGISTERED', 'Test09@test.com', '010-0000-0009', NOW(), NOW(), 'ADMIN');